apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: castai-pdb-controller
  namespace: castai-agent
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: castai-pdb-controller

