apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: castai-pdb-controller
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]  # Add this new rule for namespaces
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: castai-pdb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: castai-pdb-controller
subjects:
- kind: ServiceAccount
  name: castai-pdb-controller
  namespace: castai-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: castai-pdb-controller
  namespace: castai-agent

