apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "castai-pdb-controller.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "castai-pdb-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "castai-pdb-controller.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "castai-pdb-controller.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }} 