apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-minavailable
  annotations:
    workloads.cast.ai/pdb-minAvailable: "3"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-minavailable
  template:
    metadata:
      labels:
        app: app-minavailable
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-maxunavailable
  annotations:
    workloads.cast.ai/pdb-maxUnavailable: "10%"
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app-maxunavailable
  template:
    metadata:
      labels:
        app: app-maxunavailable
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-bypass-logic
  annotations:   
    workloads.cast.ai/bypass-default-pdb: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-bypass-logic
  template:
    metadata:
      labels:
        app: app-bypass-logic
    spec:
      containers:
        - name: nginx
          image: nginx:1.25

